chain_id = "test-cw"
n_validator = 2
n_account = 3
binary = "junod"
prefix = "juno"
denom = "stake"
coin_type = 118

[config.node.app]
minimum-gas-prices = "0.10stake"
api = { enable = true, swagger = true, enabled-unsafe-cors = true }
rosetta = { enable = false }

[config.node.config]
instrumentation = { prometheus = false }
p2p = { addr_book_strict = false, allow_duplicate_ip = true }

[config.genesis.app_state.gov]
voting_params = { voting_period = "600s" }

[config.genesis.app_state.mint]
minter = { inflation = "0.300000000000000000" }
